SET PAGES 0
SET FEED  OFF
SPOOL COMPILA.LST
SELECT 'ALTER '||decode(OBJECT_TYPE,'UNDEFINED','SNAPSHOT',OBJECT_TYPE)||' "'||OBJECT_NAME||'" COMPILE;'
FROM USER_OBJECTS
WHERE STATUS  = 'INVALID'
AND   OBJECT_TYPE <> 'PACKAGE BODY'
UNION
SELECT 'ALTER PACKAGE "'||OBJECT_NAME||'" COMPILE BODY;'
FROM USER_OBJECTS
WHERE STATUS  = 'INVALID'
AND   OBJECT_TYPE = 'PACKAGE BODY'
/
SPOOL OFF
SET FEED ON
SET PAGES 24
START COMPILA.LST
set pages 1000
