SET PAGES 0
SET FEED  OFF
SPOOL COMPILA_DBA.LST
SELECT 'ALTER '||DECODE(OBJECT_TYPE,'UNDEFINED','SNAPSHOT',OBJECT_TYPE)||' '||OWNER||'.'||OBJECT_NAME||'  COMPILE;'
FROM DBA_OBJECTS
WHERE STATUS  = 'INVALID'
AND   OBJECT_TYPE NOT IN ('PACKAGE BODY','TYPE BODY')
UNION
SELECT 'ALTER PACKAGE '||OWNER||'.'||OBJECT_NAME||' COMPILE BODY;'
FROM DBA_OBJECTS
WHERE STATUS  = 'INVALID'
and owner <> 'SYS' 
AND   OBJECT_TYPE = ('PACKAGE BODY')
UNION
SELECT 'ALTER TYPE '||OWNER||'.'||OBJECT_NAME||' COMPILE BODY;'
FROM DBA_OBJECTS
WHERE STATUS  = 'INVALID'
AND   OBJECT_TYPE = ('TYPE BODY')
/

SPOOL OFF
SET FEED ON
SET PAGES 24
START COMPILA_DBA.LST
set pages 1000
