16:55:14 PNXTL12.DBASCON>
16:55:14 PNXTL12.DBASCON>SELECT
16:55:14   2  'GRANT '||DECODE(OBJECT_TYPE,'SEQUENCE','SELECT','EXECUTE')||'  ON  LOG.'||OBJECT_NAME ||' TO RLOG_UPDATE;'
16:55:14   3  FROM dba_OBJECTS
16:55:14   4  WHERE  OBJECT_TYPE IN ('PROCEDURE','SEQUENCE','PACKAGE', 'FUNCTION')
16:55:14   5  and  owner = 'LOG'
16:55:14   6  UNION
16:55:14   7  SELECT 'GRANT SELECT, INSERT,DELETE, UPDATE ON LOG.'||OBJECT_NAME ||' TO RLOG_UPDATE;'
16:55:14   8  FROM dba_OBJECTS
16:55:14   9  WHERE OBJECT_TYPE IN ('TABLE')
16:55:14  10  and  owner = 'LOG'
16:55:14  11  UNION
16:55:14  12  SELECT 'GRANT SELECT ON LOG.'||OBJECT_NAME ||' TO RLOG_SELECT;'
16:55:15  13  FROM dba_OBJECTS
16:55:15  14  WHERE OBJECT_TYPE IN ('TABLE','VIEW')
16:55:15  15  and  owner = 'LOG'
16:55:15  16  /

'GRANT'||DECODE(OBJECT_TYPE,'SEQUENCE','SELECT','EXECUTE')||'ONLOG.'||OBJECT_NAME||'TORLOG_UPDATE;'
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
GRANT SELECT ON LOG.G_LOG_ATTRS TO RLOG_SELECT;
GRANT SELECT ON LOG.G_LOG_ATTRS_BKP TO RLOG_SELECT;
GRANT SELECT ON LOG.G_LOG_GETIDRANGEREQ TO RLOG_SELECT;
GRANT SELECT ON LOG.G_LOG_MESSAGES TO RLOG_SELECT;
GRANT SELECT ON LOG.G_LOG_MESSAGES_BKP TO RLOG_SELECT;
GRANT SELECT ON LOG.G_LOG_SCHEMA_INFO TO RLOG_SELECT;
GRANT SELECT, INSERT,DELETE, UPDATE ON LOG.G_LOG_ATTRS TO RLOG_UPDATE;
GRANT SELECT, INSERT,DELETE, UPDATE ON LOG.G_LOG_ATTRS_BKP TO RLOG_UPDATE;
GRANT SELECT, INSERT,DELETE, UPDATE ON LOG.G_LOG_GETIDRANGEREQ TO RLOG_UPDATE;
GRANT SELECT, INSERT,DELETE, UPDATE ON LOG.G_LOG_MESSAGES TO RLOG_UPDATE;
GRANT SELECT, INSERT,DELETE, UPDATE ON LOG.G_LOG_MESSAGES_BKP TO RLOG_UPDATE;
GRANT SELECT, INSERT,DELETE, UPDATE ON LOG.G_LOG_SCHEMA_INFO TO RLOG_UPDATE;

12 rows selected.

16:55:18 PNXTL12.DBASCON>spool off;
