COLUMN OWNER FORMAT A10
COLUMN OBJECT_NAME FORMAT A30
COLUMN OBJECT_TYPE FORMAT A16
SELECT OWNER
     , OBJECT_NAME
     , OBJECT_TYPE
     , CREATED 
     , LAST_DDL_TIME 
     , TIMESTAMP 
     , STATUS
  FROM DBA_OBJECTS 
 WHERE OBJECT_NAME LIKE UPPER('%&OBJETO%') 
   AND OWNER LIKE UPPER('%&OWNER%')
/