13:16:20 A1NXTL08.OP_PNET2>/

'GRANTBSCS_ROLETO'||USERNAME||';'
--------------------------------------------------
GRANT BSCS_ROLE TO ACDSOUZA;
GRANT BSCS_ROLE TO AMOT2;
GRANT BSCS_ROLE TO CFABRICI;
GRANT BSCS_ROLE TO CNASCIM8;
GRANT BSCS_ROLE TO COLIVE11;
GRANT BSCS_ROLE TO CRAZERA;
GRANT BSCS_ROLE TO CSIL54;
GRANT BSCS_ROLE TO CVICENTE;
GRANT BSCS_ROLE TO DSANT22;
GRANT BSCS_ROLE TO DSILVA1;
GRANT BSCS_ROLE TO EFRANCI2;
GRANT BSCS_ROLE TO ELOBO;
GRANT BSCS_ROLE TO ESANT11;
GRANT BSCS_ROLE TO ESANT30;
GRANT BSCS_ROLE TO FALMEID6;
GRANT BSCS_ROLE TO FBATIST3;
GRANT BSCS_ROLE TO FBRIT2;
GRANT BSCS_ROLE TO GALVES;
GRANT BSCS_ROLE TO HBORGES;
GRANT BSCS_ROLE TO JGOIS;
GRANT BSCS_ROLE TO JJUNI18;
GRANT BSCS_ROLE TO JMOURA;
GRANT BSCS_ROLE TO JNASCIM5;
GRANT BSCS_ROLE TO LCAETAN2;
GRANT BSCS_ROLE TO LJUNIO9;
GRANT BSCS_ROLE TO LMORAIS;
GRANT BSCS_ROLE TO LPEREIR4;
GRANT BSCS_ROLE TO LPINHEI;
GRANT BSCS_ROLE TO LSIL40;
GRANT BSCS_ROLE TO LSOUSA;
GRANT BSCS_ROLE TO MAOLIVEI;
GRANT BSCS_ROLE TO MBIZZO;
GRANT BSCS_ROLE TO MGASPAR;
GRANT BSCS_ROLE TO MSANTO1;
GRANT BSCS_ROLE TO MSERNAGL;
GRANT BSCS_ROLE TO PALMEID3;
GRANT BSCS_ROLE TO PCORRE3;
GRANT BSCS_ROLE TO PDAMASCE;
GRANT BSCS_ROLE TO PSIMOES;
GRANT BSCS_ROLE TO PSOUS2;
GRANT BSCS_ROLE TO RAQUIN2;
GRANT BSCS_ROLE TO RARAUJ1;
GRANT BSCS_ROLE TO RBASTO2;
GRANT BSCS_ROLE TO RCARNEIR;
GRANT BSCS_ROLE TO RCOS13;
GRANT BSCS_ROLE TO RJUNIO7;
GRANT BSCS_ROLE TO RLI10;
GRANT BSCS_ROLE TO RMANFRED;
GRANT BSCS_ROLE TO RPEREIR;
GRANT BSCS_ROLE TO RSENNA;
GRANT BSCS_ROLE TO RSIL41;
GRANT BSCS_ROLE TO SBORGES;
GRANT BSCS_ROLE TO SOLIVEI;
GRANT BSCS_ROLE TO SRIBEIR5;
GRANT BSCS_ROLE TO TGANDOLF;
GRANT BSCS_ROLE TO TLYRA;
GRANT BSCS_ROLE TO TOLIVEIR;
GRANT BSCS_ROLE TO TVEREDA;
GRANT BSCS_ROLE TO VMAGALHA;
GRANT BSCS_ROLE TO VOLIVEI2;
GRANT BSCS_ROLE TO VSOUZ8;
GRANT BSCS_ROLE TO WSANTO2;

62 linhas selecionadas.

13:16:21 A1NXTL08.OP_PNET2>spool off;
