ACCEPT USUARIO PROMPT 'Entre com o Nome do Usuário: '
SELECT 
SUBSTR(USERNAME,1,15) USUARIO,
SUBSTR(ACCOUNT_STATUS,1,16) STATUS,
SUBSTR(TEMPORARY_TABLESPACE,1,20) TEMP,
SUBSTR(DEFAULT_TABLESPACE,1,20) TABLESPACE,
CREATED, 
SUBSTR(PASSWORD,1,16) SENHA,
SUBSTR(PROFILE,1,18) PROFILE
FROM 
DBA_USERS WHERE USERNAME LIKE UPPER('%&USUARIO%')
order by username;
