set timing on;


drop materialized view bix.MV_BILLCYCLE_ASSIGNMENT_HIST;
drop materialized view bix.MV_BILLING_IDENTIFIER;
drop materialized view bix.MV_CONTRACT_ALL;
drop materialized view bix.MV_CONTR_DEVICES;
drop materialized view bix.MV_CONTR_SERVICES_CAP;
drop materialized view bix.MV_DIRECTORY_NUMBER;
drop materialized view bix.MV_MPDPLTAB;
drop materialized view bix.MV_MPULKGVM;
drop materialized view bix.MV_MPULKTMM;
drop materialized view bix.MV_MPULKTWM;
drop materialized view bix.MV_MPULKUPM;
drop materialized view bix.MV_MPURHTAB;
drop materialized view bix.MV_MPURIVSD;
drop materialized view bix.MV_MPUSNTAB;
drop materialized view bix.MV_MPUZNTAB;
drop materialized view bix.MV_MPUZOTAB;
drop materialized view bix.MV_MPUZPTAB;
drop materialized view bix.MV_PORT;
drop materialized view bix.MV_PR_SERV_SPCODE_HIST;
drop materialized view bix.MV_RATEPLAN;
drop materialized view bix.MV_RATEPLAN_HIST;
drop materialized view bix.MV_RATEPLAN_VERSION;
drop materialized view bix.MV_THSFTTAB;
drop materialized view bix.MV_THUFITAB;
drop materialized view bix.MV_UDC_RATE_TYPE_TABLE;


---


CREATE MATERIALIZED VIEW "BIX"."MV_BILLCYCLE_ASSIGNMENT_HIST"
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 1048576000 NEXT 1048576000 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIX_DAT"
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 1048576000 NEXT 1048576000 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIX_DAT"
  REFRESH FAST ON DEMAND NEXT null
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  DISABLE QUERY REWRITE
  AS SELECT "BILLCYCLE_ASSIGNMENT_HISTORY"."CUSTOMER_ID" "CUSTOMER_ID","BILLCYCLE_ASSIGNMENT_HISTORY"."SEQNO" "SEQNO","BILLCYCLE_ASSIGNMENT_HISTORY"."BILLCYCLE" "BILLCYCLE","BILLCYCLE_ASSIGNMENT_HISTORY"."VALID_FROM" "VALID_FROM","BILLCYCLE_ASSIGNMENT_HISTORY"."REASON_ID" "REASON_ID","BILLCYCLE_ASSIGNMENT_HISTORY"."USERNAME" "USERNAME","BILLCYCLE_ASSIGNMENT_HISTORY"."COMMENTS" "COMMENTS" FROM "SYSADM"."BILLCYCLE_ASSIGNMENT_HISTORY"@LNK.MIT08 "BILLCYCLE_ASSIGNMENT_HISTORY"
  /
  

  CREATE MATERIALIZED VIEW "BIX"."MV_BILLING_IDENTIFIER"
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 1048576000 NEXT 1048576000 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIX_DAT"
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 1048576000 NEXT 1048576000 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIX_DAT"
  REFRESH FAST ON DEMAND NEXT null
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  DISABLE QUERY REWRITE
  AS SELECT "BILLING_IDENTIFIER"."BID_ID" "BID_ID","BILLING_IDENTIFIER"."REC_VERSION" "REC_VERSION","BILLING_IDENTIFIER"."BID_TYPE" "BID_TYPE","BILLING_IDENTIFIER"."NETWORK_ID" "NETWORK_ID","BILLING_IDENTIFIER"."PARENT_SID_ID" "PARENT_SID_ID","BILLING_IDENTIFIER"."BID_GROUP_ID" "BID_GROUP_ID","BILLING_IDENTIFIER"."BID_DESC" "BID_DESC","BILLING_IDENTIFIER"."IMPORT_EXPORT_FLAG" "IMPORT_EXPORT_FLAG" FROM "SYSADM"."BILLING_IDENTIFIER"@LNK.MIT08 "BILLING_IDENTIFIER"
  /


  CREATE MATERIALIZED VIEW "BIX"."MV_CONTRACT_ALL"
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 1048576000 NEXT 1048576000 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIX_DAT"
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 1048576000 NEXT 1048576000 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIX_DAT"
  REFRESH FAST ON DEMAND NEXT null
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  DISABLE QUERY REWRITE
  AS SELECT "CONTRACT_ALL"."CO_ID" "CO_ID","CONTRACT_ALL"."CUSTOMER_ID" "CUSTOMER_ID","CONTRACT_ALL"."TYPE" "TYPE","CONTRACT_ALL"."PLCODE" "PLCODE",
  "CONTRACT_ALL"."SCCODE" "SCCODE","CONTRACT_ALL"."SUBM_ID" "SUBM_ID","CONTRACT_ALL"."CO_SIGNED" "CO_SIGNED","CONTRACT_ALL"."CO_EQU_TYPE" "CO_EQU_TYPE",
  "CONTRACT_ALL"."CO_REP_BILL" "CO_REP_BILL","CONTRACT_ALL"."CO_REP" "CO_REP","CONTRACT_ALL"."CO_REP_BILL_IDNO" "CO_REP_BILL_IDNO",
  "CONTRACT_ALL"."CO_REP_IDNO" "CO_REP_IDNO","CONTRACT_ALL"."CO_INSTALLED" "CO_INSTALLED","CONTRACT_ALL"."CO_ARCHIVE" "CO_ARCHIVE",
  "CONTRACT_ALL"."CO_DIR_ENTRY" "CO_DIR_ENTRY","CONTRACT_ALL"."CO_OPERATOR_DIR" "CO_OPERATOR_DIR","CONTRACT_ALL"."CO_PSTN_DIR" "CO_PSTN_DIR",
  "CONTRACT_ALL"."CO_ASS_SERV" "CO_ASS_SERV","CONTRACT_ALL"."CO_ASS_EQU" "CO_ASS_EQU","CONTRACT_ALL"."CO_CRD_CHECK" "CO_CRD_CHECK",
  "CONTRACT_ALL"."CO_CRD_CHK_END" "CO_CRD_CHK_END","CONTRACT_ALL"."CO_CRD_CHK_START" "CO_CRD_CHK_START","CONTRACT_ALL"."CO_CRD_CLICKS" "CO_CRD_CLICKS",
  "CONTRACT_ALL"."CO_CRD_CLICKS_DAY" "CO_CRD_CLICKS_DAY","CONTRACT_ALL"."CO_CRD_DAYS" "CO_CRD_DAYS","CONTRACT_ALL"."CO_COMMENT" "CO_COMMENT",
  "CONTRACT_ALL"."CO_RESERVED" "CO_RESERVED","CONTRACT_ALL"."CO_EXPIR_DATE" "CO_EXPIR_DATE","CONTRACT_ALL"."CO_ACTIVATED" "CO_ACTIVATED",
  "CONTRACT_ALL"."CO_ENTDATE" "CO_ENTDATE","CONTRACT_ALL"."CO_MODDATE" "CO_MODDATE","CONTRACT_ALL"."CO_USERLASTMOD" "CO_USERLASTMOD",
  "CONTRACT_ALL"."TMCODE" "TMCODE","CONTRACT_ALL"."TMCODE_DATE" "TMCODE_DATE","CONTRACT_ALL"."CO_CRD_D_TR1" "CO_CRD_D_TR1",
  "CONTRACT_ALL"."CO_CRD_D_TR2" "CO_CRD_D_TR2","CONTRACT_ALL"."CO_CRD_D_TR3" "CO_CRD_D_TR3","CONTRACT_ALL"."CO_CRD_P_TR1" "CO_CRD_P_TR1",
  "CONTRACT_ALL"."CO_CRD_P_TR2" "CO_CRD_P_TR2","CONTRACT_ALL"."CO_CRD_P_TR3" "CO_CRD_P_TR3","CONTRACT_ALL"."ECCODE_LDC" "ECCODE_LDC",
  "CONTRACT_ALL"."PENDING_ECCODE_LDC" "PENDING_ECCODE_LDC","CONTRACT_ALL"."ECCODE_LEC" "ECCODE_LEC","CONTRACT_ALL"."PENDING_ECCODE_LEC" "PENDING_ECCODE_LEC",
  "CONTRACT_ALL"."CO_REQUEST" "CO_REQUEST","CONTRACT_ALL"."DEALER_ID" "DEALER_ID","CONTRACT_ALL"."NOT_VALID" "NOT_VALID","CONTRACT_ALL"."ARPCODE" "ARPCODE",
  "CONTRACT_ALL"."CO_ADDR_ON_IBILL" "CO_ADDR_ON_IBILL","CONTRACT_ALL"."CO_CRD_AMOUNT" "CO_CRD_AMOUNT","CONTRACT_ALL"."CO_CRD_AMOUNT_DAY" "CO_CRD_AMOUNT_DAY",
  "CONTRACT_ALL"."PRODUCT_HISTORY_DATE" "PRODUCT_HISTORY_DATE","CONTRACT_ALL"."CO_CONFIRM" "CO_CONFIRM","CONTRACT_ALL"."CO_EXT_CSUIN" "CO_EXT_CSUIN",
  "CONTRACT_ALL"."TRIAL_END_DATE" "TRIAL_END_DATE","CONTRACT_ALL"."CO_IB_CDR_FLAG" "CO_IB_CDR_FLAG","CONTRACT_ALL"."CURRENCY" "CURRENCY",
  "CONTRACT_ALL"."REC_VERSION" "REC_VERSION","CONTRACT_ALL"."AN_PACKAGE_ID" "AN_PACKAGE_ID","CONTRACT_ALL"."CO_REL_TYPE" "CO_REL_TYPE",
  "CONTRACT_ALL"."PENDING_TMCODE" "PENDING_TMCODE","CONTRACT_ALL"."CONTRACT_TEMPLATE" "CONTRACT_TEMPLATE","CONTRACT_ALL"."CO_CODE" "CO_CODE",
  "CONTRACT_ALL"."BUSINESS_UNIT_ID" "BUSINESS_UNIT_ID","CONTRACT_ALL"."DESCRIPTION" "DESCRIPTION","CONTRACT_ALL"."AGREEMENT_TYPE" "AGREEMENT_TYPE",
  "CONTRACT_ALL"."EXT_PRODUCT_ID" "EXT_PRODUCT_ID","CONTRACT_ALL"."REMOTE_PLCODE" "REMOTE_PLCODE","CONTRACT_ALL"."ECCODE" "ECCODE",
  "CONTRACT_ALL"."HPLMN_BID_GROUP_ID" "HPLMN_BID_GROUP_ID","CONTRACT_ALL"."VPLMN_BID_GROUP_ID" "VPLMN_BID_GROUP_ID","CONTRACT_ALL"."HOME_PARTY_ID" "HOME_PARTY_ID",
  "CONTRACT_ALL"."CONTRACT_TYPE_ID" "CONTRACT_TYPE_ID","CONTRACT_ALL"."TRIAL_START_DATE" "TRIAL_START_DATE","CONTRACT_ALL"."FOH_AGGREGATION_FLAG" "FOH_AGGREGATION_FLAG",
  "CONTRACT_ALL"."GL_ACC_PACK_ID" "GL_ACC_PACK_ID","CONTRACT_ALL"."CDS_BILL_MEDIUM" "CDS_BILL_MEDIUM","CONTRACT_ALL"."CDS_GENERATION" "CDS_GENERATION",
  "CONTRACT_ALL"."CHARGE_PART_NUM" "CHARGE_PART_NUM","CONTRACT_ALL"."CH_STATUS" "CH_STATUS","CONTRACT_ALL"."SVP_FILE" "SVP_FILE",
  "CONTRACT_ALL"."SALES_CONTACT_ID" "SALES_CONTACT_ID","CONTRACT_ALL"."COM_START_DATE" "COM_START_DATE","CONTRACT_ALL"."COM_END_DATE" "COM_END_DATE",
  "CONTRACT_ALL"."COM_MIN_DURATION" "COM_MIN_DURATION","CONTRACT_ALL"."REASON_CODE" "REASON_CODE","CONTRACT_ALL"."ACTION_DATE" "ACTION_DATE",
  "CONTRACT_ALL"."COM_MIN_RENOCO_MONTHS" "COM_MIN_RENOCO_MONTHS","CONTRACT_ALL"."RATEPLAN_CHANGE_DATE" "RATEPLAN_CHANGE_DATE","CONTRACT_ALL"."TMCODE_OLD" "TMCODE_OLD",
  "CONTRACT_ALL"."REASON_CODE_PENDING" "REASON_CODE_PENDING","CONTRACT_ALL"."COM_MIN_RENOCO_MONTHS_PENDING" "COM_MIN_RENOCO_MONTHS_PENDING",
  "CONTRACT_ALL"."SALES_ZONE_ID" "SALES_ZONE_ID","CONTRACT_ALL"."CREDIT_VALUE" "CREDIT_VALUE","CONTRACT_ALL"."CREDIT_QUAL_CHECK" "CREDIT_QUAL_CHECK",
  "CONTRACT_ALL"."CREDIT_QUAL_VALUE" "CREDIT_QUAL_VALUE","CONTRACT_ALL"."AGING_SCORE" "AGING_SCORE","CONTRACT_ALL"."SUSPENSION_SCORE" "SUSPENSION_SCORE",
  "CONTRACT_ALL"."CONTRACT_BILLING_AVG" "CONTRACT_BILLING_AVG","CONTRACT_ALL"."CREDIT_SCORE" "CREDIT_SCORE","CONTRACT_ALL"."CH_STATUS_VALIDFROM" "CH_STATUS_VALIDFROM" 
  FROM "SYSADM"."CONTRACT_ALL"@LNK.MIT08 "CONTRACT_ALL"
  /



  CREATE MATERIALIZED VIEW "BIX"."MV_CONTR_DEVICES"
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 1048576000 NEXT 1048576000 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIX_DAT"
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 1048576000 NEXT 1048576000 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIX_DAT"
  REFRESH FAST ON DEMAND NEXT null
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  DISABLE QUERY REWRITE
  AS SELECT "CONTR_DEVICES"."CD_ID" "CD_ID","CONTR_DEVICES"."CD_SEQNO" "CD_SEQNO","CONTR_DEVICES"."CO_ID" "CO_ID","CONTR_DEVICES"."PORT_ID" "PORT_ID",
  "CONTR_DEVICES"."DN_ID" "DN_ID","CONTR_DEVICES"."EQ_ID" "EQ_ID","CONTR_DEVICES"."CD_STATUS" "CD_STATUS","CONTR_DEVICES"."CD_ACTIV_DATE" "CD_ACTIV_DATE",
  "CONTR_DEVICES"."CD_DEACTIV_DATE" "CD_DEACTIV_DATE","CONTR_DEVICES"."CD_VALIDFROM" "CD_VALIDFROM","CONTR_DEVICES"."CD_ENTDATE" "CD_ENTDATE",
  "CONTR_DEVICES"."CD_MODDATE" "CD_MODDATE","CONTR_DEVICES"."CD_USERLASTMOD" "CD_USERLASTMOD","CONTR_DEVICES"."CD_SM_NUM" "CD_SM_NUM",
  "CONTR_DEVICES"."CD_CHANNELS" "CD_CHANNELS","CONTR_DEVICES"."CD_CHANNELS_EXCL" "CD_CHANNELS_EXCL","CONTR_DEVICES"."CD_EQ_NUM" "CD_EQ_NUM",
  "CONTR_DEVICES"."CD_PENDING_STATE" "CD_PENDING_STATE","CONTR_DEVICES"."CD_RS_ID" "CD_RS_ID","CONTR_DEVICES"."CD_PLCODE" "CD_PLCODE",
  "CONTR_DEVICES"."HLCODE" "HLCODE","CONTR_DEVICES"."REC_VERSION" "REC_VERSION" FROM "SYSADM"."CONTR_DEVICES"@LNK.MIT08 "CONTR_DEVICES"
  /



  CREATE MATERIALIZED VIEW "BIX"."MV_CONTR_SERVICES_CAP"
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 1048576000 NEXT 1048576000 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIX_DAT"
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 1048576000 NEXT 1048576000 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIX_DAT"
  REFRESH FAST ON DEMAND NEXT null
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  DISABLE QUERY REWRITE
  AS SELECT "CONTR_SERVICES_CAP"."CO_ID" "CO_ID","CONTR_SERVICES_CAP"."SNCODE" "SNCODE","CONTR_SERVICES_CAP"."SEQNO" "SEQNO","CONTR_SERVICES_CAP"."SEQNO_PRE" "SEQNO_PRE",
  "CONTR_SERVICES_CAP"."BCCODE" "BCCODE","CONTR_SERVICES_CAP"."PENDING_BCCODE" "PENDING_BCCODE","CONTR_SERVICES_CAP"."DN_ID" "DN_ID",
  "CONTR_SERVICES_CAP"."DN_BLOCK_ID" "DN_BLOCK_ID","CONTR_SERVICES_CAP"."MAIN_DIRNUM" "MAIN_DIRNUM","CONTR_SERVICES_CAP"."CS_STATUS" "CS_STATUS",
  "CONTR_SERVICES_CAP"."CS_ACTIV_DATE" "CS_ACTIV_DATE","CONTR_SERVICES_CAP"."CS_DEACTIV_DATE" "CS_DEACTIV_DATE","CONTR_SERVICES_CAP"."CS_REQUEST" "CS_REQUEST",
  "CONTR_SERVICES_CAP"."REC_VERSION" "REC_VERSION","CONTR_SERVICES_CAP"."PUBLIC_NUMBER_DN_ID" "PUBLIC_NUMBER_DN_ID","CONTR_SERVICES_CAP"."VPN_ID" "VPN_ID",
  "CONTR_SERVICES_CAP"."PUBLIC_BLOCK_ID" "PUBLIC_BLOCK_ID","CONTR_SERVICES_CAP"."PROFILE_ID" "PROFILE_ID","CONTR_SERVICES_CAP"."DN_SHOWN_IN_BILL" "DN_SHOWN_IN_BILL",
  "CONTR_SERVICES_CAP"."ENTRY_USER" "ENTRY_USER","CONTR_SERVICES_CAP"."ENTRY_DATE" "ENTRY_DATE","CONTR_SERVICES_CAP"."CHILD_CS_REQUEST" "CHILD_CS_REQUEST" 
  FROM "SYSADM"."CONTR_SERVICES_CAP"@LNK.MIT08 "CONTR_SERVICES_CAP"
  /


  CREATE MATERIALIZED VIEW "BIX"."MV_DIRECTORY_NUMBER"
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 1048576000 NEXT 1048576000 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIX_DAT"
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 1048576000 NEXT 1048576000 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIX_DAT"
  REFRESH FAST ON DEMAND NEXT null
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  DISABLE QUERY REWRITE
  AS SELECT "DIRECTORY_NUMBER"."DN_ID" "DN_ID","DIRECTORY_NUMBER"."PLCODE" "PLCODE","DIRECTORY_NUMBER"."NDC" "NDC","DIRECTORY_NUMBER"."HLCODE" "HLCODE",
  "DIRECTORY_NUMBER"."DN_NUM" "DN_NUM","DIRECTORY_NUMBER"."DN_STATUS" "DN_STATUS","DIRECTORY_NUMBER"."DN_STATUS_MOD_DATE" "DN_STATUS_MOD_DATE",
  "DIRECTORY_NUMBER"."DEALER_ID" "DEALER_ID","DIRECTORY_NUMBER"."DN_ASSIGN_DATE" "DN_ASSIGN_DATE","DIRECTORY_NUMBER"."DN_PHONE_FLAG" "DN_PHONE_FLAG",
  "DIRECTORY_NUMBER"."DN_TYPE" "DN_TYPE","DIRECTORY_NUMBER"."DN_STATUS_REQU" "DN_STATUS_REQU","DIRECTORY_NUMBER"."DN_STA_REQU_DATE" "DN_STA_REQU_DATE",
  "DIRECTORY_NUMBER"."DN_ASSIGN" "DN_ASSIGN","DIRECTORY_NUMBER"."DN_ENTDATE" "DN_ENTDATE","DIRECTORY_NUMBER"."DN_MODDATE" "DN_MODDATE",
  "DIRECTORY_NUMBER"."DN_MODFLAG" "DN_MODFLAG","DIRECTORY_NUMBER"."DN_AUTH" "DN_AUTH","DIRECTORY_NUMBER"."EVCODE" "EVCODE","DIRECTORY_NUMBER"."HMCODE" "HMCODE",
  "DIRECTORY_NUMBER"."LOCAL_PREFIX_LEN" "LOCAL_PREFIX_LEN","DIRECTORY_NUMBER"."SIMPOH_ID" "SIMPOH_ID","DIRECTORY_NUMBER"."SIMPOT_ID" "SIMPOT_ID",
  "DIRECTORY_NUMBER"."SIMPOT_BATCH" "SIMPOT_BATCH","DIRECTORY_NUMBER"."EXTERNAL_IND" "EXTERNAL_IND","DIRECTORY_NUMBER"."BLOCK_IND" "BLOCK_IND",
  "DIRECTORY_NUMBER"."EXTENSION_LENGTH_MAX" "EXTENSION_LENGTH_MAX","DIRECTORY_NUMBER"."DN_AUTH_PENDING" "DN_AUTH_PENDING","DIRECTORY_NUMBER"."REC_VERSION" "REC_VERSION",
  "DIRECTORY_NUMBER"."DIRNUM_NPCODE" "DIRNUM_NPCODE","DIRECTORY_NUMBER"."VPN_ID" "VPN_ID","DIRECTORY_NUMBER"."STATIC_PDP_REQUIRED" "STATIC_PDP_REQUIRED",
  "DIRECTORY_NUMBER"."ROAMING_ALLOWED" "ROAMING_ALLOWED","DIRECTORY_NUMBER"."TRANSACTION_ID" "TRANSACTION_ID","DIRECTORY_NUMBER"."BUSINESS_UNIT_ID" "BUSINESS_UNIT_ID",
  "DIRECTORY_NUMBER"."MEMBER_ALIAS" "MEMBER_ALIAS","DIRECTORY_NUMBER"."UB_ID" "UB_ID","DIRECTORY_NUMBER"."RESTRICTED_FLEET" "RESTRICTED_FLEET",
  "DIRECTORY_NUMBER"."MEMBER_ID" "MEMBER_ID","DIRECTORY_NUMBER"."FLEET_ID" "FLEET_ID","DIRECTORY_NUMBER"."EXPIRATION_DATE" "EXPIRATION_DATE",
  "DIRECTORY_NUMBER"."AREA_ID" "AREA_ID" FROM "SYSADM"."DIRECTORY_NUMBER"@LNK.MIT08 "DIRECTORY_NUMBER"
  /




  CREATE MATERIALIZED VIEW "BIX"."MV_MPDPLTAB"
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 1048576000 NEXT 1048576000 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIX_DAT"
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 1048576000 NEXT 1048576000 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIX_DAT"
  REFRESH FAST ON DEMAND NEXT null
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  DISABLE QUERY REWRITE
  AS SELECT "MPDPLTAB"."PLCODE" "PLCODE","MPDPLTAB"."SCCODE" "SCCODE","MPDPLTAB"."PLMNNAME" "PLMNNAME","MPDPLTAB"."PLMNTYPE" "PLMNTYPE","MPDPLTAB"."SHDES" "SHDES",
  "MPDPLTAB"."COUNTRY" "COUNTRY","MPDPLTAB"."INTRUNK" "INTRUNK","MPDPLTAB"."OUTTRUNK" "OUTTRUNK","MPDPLTAB"."RECONIND" "RECONIND","MPDPLTAB"."PLNETID" "PLNETID",
  "MPDPLTAB"."PLCDRID" "PLCDRID","MPDPLTAB"."CAMEL_FLAG" "CAMEL_FLAG","MPDPLTAB"."NETWORK_TYPE" "NETWORK_TYPE","MPDPLTAB"."SP_DEFDOMAIN" "SP_DEFDOMAIN",
  "MPDPLTAB"."REC_VERSION" "REC_VERSION","MPDPLTAB"."DEFAULT_NETWORK_ELEMENT_ID" "DEFAULT_NETWORK_ELEMENT_ID","MPDPLTAB"."INTER_HPLMN_ROAMING_FLAG" "INTER_HPLMN_ROAMING_FLAG",
  "MPDPLTAB"."CALL_DEST" "CALL_DEST","MPDPLTAB"."SUBM_ID" "SUBM_ID" FROM "SYSADM"."MPDPLTAB"@LNK.MIT08 "MPDPLTAB"
/



  CREATE MATERIALIZED VIEW "BIX"."MV_MPULKGVM"
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 1048576000 NEXT 1048576000 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIX_DAT"
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 1048576000 NEXT 1048576000 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIX_DAT"
  REFRESH FAST ON DEMAND NEXT null
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  DISABLE QUERY REWRITE
  AS SELECT "MPULKGVM"."GVCODE" "GVCODE","MPULKGVM"."VSCODE" "VSCODE","MPULKGVM"."VSDATE" "VSDATE","MPULKGVM"."ZNCODE" "ZNCODE","MPULKGVM"."ZOCODE" "ZOCODE",
  "MPULKGVM"."ZPCODE" "ZPCODE","MPULKGVM"."GZCODE" "GZCODE","MPULKGVM"."GZNCODE" "GZNCODE","MPULKGVM"."ZODES" "ZODES","MPULKGVM"."CGI" "CGI","MPULKGVM"."ZPDES" "ZPDES",
  "MPULKGVM"."DIGITS" "DIGITS","MPULKGVM"."OVERRIDE_GZ" "OVERRIDE_GZ","MPULKGVM"."DEST_NPCODE" "DEST_NPCODE","MPULKGVM"."REC_VERSION" "REC_VERSION",
  "MPULKGVM"."ORIGIN_NPCODE" "ORIGIN_NPCODE","MPULKGVM"."IMPORT_EXPORT_FLAG" "IMPORT_EXPORT_FLAG","MPULKGVM"."SEQNO" "SEQNO" 
  FROM "SYSADM"."MPULKGVM"@LNK.MIT08 "MPULKGVM"
/


  CREATE MATERIALIZED VIEW "BIX"."MV_MPULKTMM"
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 1048576000 NEXT 1048576000 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIX_DAT"
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 1048576000 NEXT 1048576000 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIX_DAT"
  REFRESH FAST ON DEMAND NEXT null
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  DISABLE QUERY REWRITE
  AS SELECT "MPULKTMM"."TMCODE" "TMCODE","MPULKTMM"."VSCODE" "VSCODE","MPULKTMM"."VSDATE" "VSDATE","MPULKTMM"."STATUS" "STATUS","MPULKTMM"."SPCODE" "SPCODE",
  "MPULKTMM"."SNCODE" "SNCODE","MPULKTMM"."SVLCODE" "SVLCODE","MPULKTMM"."RATEIND" "RATEIND","MPULKTMM"."UPCODE" "UPCODE","MPULKTMM"."RICODE" "RICODE",
  "MPULKTMM"."EGCODE" "EGCODE","MPULKTMM"."REC_VERSION" "REC_VERSION","MPULKTMM"."USAGE_TYPE_ID" "USAGE_TYPE_ID","MPULKTMM"."CP_PRICELIST_ID" "CP_PRICELIST_ID",
  "MPULKTMM"."FALLBACK_SRV_FLAG" "FALLBACK_SRV_FLAG" 
  FROM "SYSADM"."MPULKTMM"@LNK.MIT08 "MPULKTMM"
  /


  CREATE MATERIALIZED VIEW "BIX"."MV_MPULKTWM"
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 1048576000 NEXT 1048576000 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIX_DAT"
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 1048576000 NEXT 1048576000 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIX_DAT"
  REFRESH FAST ON DEMAND NEXT null
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  DISABLE QUERY REWRITE
  AS SELECT "MPULKTWM"."TWCODE" "TWCODE","MPULKTWM"."VSCODE" "VSCODE","MPULKTWM"."VSDATE" "VSDATE","MPULKTWM"."TTCODE" "TTCODE","MPULKTWM"."TICODE" "TICODE",
  "MPULKTWM"."TDCODE" "TDCODE","MPULKTWM"."TIDES" "TIDES","MPULKTWM"."LB" "LB","MPULKTWM"."RB" "RB","MPULKTWM"."TDDES" "TDDES","MPULKTWM"."COLDATE" "COLDATE",
  "MPULKTWM"."MON" "MON","MPULKTWM"."TUE" "TUE","MPULKTWM"."WED" "WED","MPULKTWM"."THU" "THU","MPULKTWM"."FRI" "FRI","MPULKTWM"."SAT" "SAT","MPULKTWM"."SUN" "SUN",
  "MPULKTWM"."HOL" "HOL","MPULKTWM"."REC_VERSION" "REC_VERSION","MPULKTWM"."TAP_TARIFF_TIME_ID" "TAP_TARIFF_TIME_ID","MPULKTWM"."TAP_DAY_CATEGORY_ID" "TAP_DAY_CATEGORY_ID",
  "MPULKTWM"."IMPORT_EXPORT_FLAG" "IMPORT_EXPORT_FLAG" 
  FROM "SYSADM"."MPULKTWM"@LNK.MIT08 "MPULKTWM"
  /



  CREATE MATERIALIZED VIEW "BIX"."MV_MPULKUPM"
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 1048576000 NEXT 1048576000 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIX_DAT"
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 1048576000 NEXT 1048576000 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIX_DAT"
  REFRESH FAST ON DEMAND NEXT null
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  DISABLE QUERY REWRITE
  AS SELECT "MPULKUPM"."UPCODE" "UPCODE","MPULKUPM"."VSCODE" "VSCODE","MPULKUPM"."VSDATE" "VSDATE","MPULKUPM"."GVCODE" "GVCODE","MPULKUPM"."GVVSCODE" "GVVSCODE",
  "MPULKUPM"."ZNCODE" "ZNCODE","MPULKUPM"."TWCODE" "TWCODE","MPULKUPM"."TWVSCODE" "TWVSCODE","MPULKUPM"."TTCODE" "TTCODE","MPULKUPM"."REC_VERSION" "REC_VERSION" 
  FROM "SYSADM"."MPULKUPM"@LNK.MIT08 "MPULKUPM"
  /



  CREATE MATERIALIZED VIEW "BIX"."MV_MPURHTAB"
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 1048576000 NEXT 1048576000 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIX_DAT"
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 1048576000 NEXT 1048576000 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIX_DAT"
  REFRESH FAST ON DEMAND NEXT null
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  DISABLE QUERY REWRITE
  AS SELECT "MPURHTAB"."FLDIR" "FLDIR","MPURHTAB"."FLCRE" "FLCRE","MPURHTAB"."FLSQN" "FLSQN","MPURHTAB"."FILE_PROCESS_MODE" "FILE_PROCESS_MODE","MPURHTAB"."FLSRC" "FLSRC",
  "MPURHTAB"."FLNAME" "FLNAME","MPURHTAB"."FLFCT" "FLFCT","MPURHTAB"."FLLCT" "FLLCT","MPURHTAB"."FLIRC" "FLIRC","MPURHTAB"."FLTOTMOC" "FLTOTMOC","MPURHTAB"."FLTOTMTC" "FLTOTMTC",
  "MPURHTAB"."FLSTATUS" "FLSTATUS","MPURHTAB"."FLBILLSTATUS" "FLBILLSTATUS","MPURHTAB"."FLTOTEVT" "FLTOTEVT","MPURHTAB"."FLTOTVAS" "FLTOTVAS","MPURHTAB"."TV_CODE" "TV_CODE",
  "MPURHTAB"."CUT_OFF_DATE" "CUT_OFF_DATE","MPURHTAB"."TOT_XFILE_CHARGE" "TOT_XFILE_CHARGE","MPURHTAB"."TAX_INCLUSIVE_IND" "TAX_INCLUSIVE_IND",
  "MPURHTAB"."TOT_GROSS_HCURR" "TOT_GROSS_HCURR","MPURHTAB"."TOT_TAX_HCURR" "TOT_TAX_HCURR","MPURHTAB"."TOT_GROSS_FORCURR" "TOT_GROSS_FORCURR",
  "MPURHTAB"."TOT_TAX_FORCURR" "TOT_TAX_FORCURR","MPURHTAB"."CURRENCY" "CURRENCY","MPURHTAB"."TOT_CAMEL_FEE" "TOT_CAMEL_FEE","MPURHTAB"."TOT_TOLL_CHARGE" "TOT_TOLL_CHARGE",
  "MPURHTAB"."REC_VERSION" "REC_VERSION","MPURHTAB"."FATAL_ERROR_FLAG" "FATAL_ERROR_FLAG","MPURHTAB"."TAP_CURRENCY" "TAP_CURRENCY","MPURHTAB"."HPLCODE" "HPLCODE",
  "MPURHTAB"."VPLCODE" "VPLCODE","MPURHTAB"."DISC_AMT_FORCURR" "DISC_AMT_FORCURR","MPURHTAB"."DISC_AMT_HCURR" "DISC_AMT_HCURR",
  "MPURHTAB"."TOT_ADVISE_NPAID_HCURR" "TOT_ADVISE_NPAID_HCURR","MPURHTAB"."TOT_ADVISE_NPAID_FCURR" "TOT_ADVISE_NPAID_FCURR","MPURHTAB"."TOT_ADVISE_HCURR" "TOT_ADVISE_HCURR",
  "MPURHTAB"."TOT_ADVISE_FCURR" "TOT_ADVISE_FCURR","MPURHTAB"."TOT_COMMISSION_HCURR" "TOT_COMMISSION_HCURR","MPURHTAB"."TOT_COMMISSION_FCURR" "TOT_COMMISSION_FCURR",
  "MPURHTAB"."TOT_ADVISE_NCOM_HCURR" "TOT_ADVISE_NCOM_HCURR","MPURHTAB"."TOT_ADVISE_NCOM_FCURR" "TOT_ADVISE_NCOM_FCURR","MPURHTAB"."TOT_REFUND_HCURR" "TOT_REFUND_HCURR",
  "MPURHTAB"."TOT_REFUND_FCURR" "TOT_REFUND_FCURR","MPURHTAB"."TOT_TAX_REF_HCURR" "TOT_TAX_REF_HCURR","MPURHTAB"."TOT_TAX_REF_FCURR" "TOT_TAX_REF_FCURR",
  "MPURHTAB"."TOT_DISCOUNT_REF_HCURR" "TOT_DISCOUNT_REF_HCURR","MPURHTAB"."TOT_DISCOUNT_REF_FCURR" "TOT_DISCOUNT_REF_FCURR",
  "MPURHTAB"."TOT_ADVISE_REF_NPAID_HCURR" "TOT_ADVISE_REF_NPAID_HCURR","MPURHTAB"."TOT_ADVISE_REF_NPAID_FCURR" "TOT_ADVISE_REF_NPAID_FCURR",
  "MPURHTAB"."TOT_ADVISE_REF_HCURR" "TOT_ADVISE_REF_HCURR","MPURHTAB"."TOT_ADVISE_REF_FCURR" "TOT_ADVISE_REF_FCURR","MPURHTAB"."TOT_COM_REF_HCURR" "TOT_COM_REF_HCURR",
  "MPURHTAB"."TOT_COM_REF_FCURR" "TOT_COM_REF_FCURR","MPURHTAB"."TOT_ADVISE_REF_NCOM_HCURR" "TOT_ADVISE_REF_NCOM_HCURR",
  "MPURHTAB"."TOT_ADVISE_REF_NCOM_FCURR" "TOT_ADVISE_REF_NCOM_FCURR","MPURHTAB"."FLTOTGPRS" "FLTOTGPRS","MPURHTAB"."FLTOTSCU" "FLTOTSCU","MPURHTAB"."FLTOTCT" "FLTOTCT",
  "MPURHTAB"."FLTOTLCS" "FLTOTLCS","MPURHTAB"."FILE_TYPE" "FILE_TYPE" 
  FROM "SYSADM"."MPURHTAB"@LNK.MIT08 "MPURHTAB"
  /



cREATE MATERIALIZED VIEW "BIX"."MV_MPURIVSD"
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 1048576000 NEXT 1048576000 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIX_DAT"
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 1048576000 NEXT 1048576000 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIX_DAT"
  REFRESH FAST ON DEMAND NEXT null
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  DISABLE QUERY REWRITE
  AS SELECT "MPURIVSD"."RICODE" "RICODE","MPURIVSD"."VSCODE" "VSCODE","MPURIVSD"."VSDATE" "VSDATE","MPURIVSD"."STATUS" "STATUS","MPURIVSD"."CHECKRC" "CHECKRC",
  "MPURIVSD"."APDATE" "APDATE","MPURIVSD"."UPCODE" "UPCODE","MPURIVSD"."UPVSCODE" "UPVSCODE","MPURIVSD"."USERLASTMOD" "USERLASTMOD","MPURIVSD"."MODDATE" "MODDATE",
  "MPURIVSD"."DROP_INPUT_THRESHOLD" "DROP_INPUT_THRESHOLD","MPURIVSD"."REC_VERSION" "REC_VERSION","MPURIVSD"."IMPORT_EXPORT_FLAG" "IMPORT_EXPORT_FLAG",
  "MPURIVSD"."INT_SYNC" "INT_SYNC" 
  FROM "SYSADM"."MPURIVSD"@LNK.MIT08 "MPURIVSD"
  /



  CREATE MATERIALIZED VIEW "BIX"."MV_MPUSNTAB"
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 1048576000 NEXT 1048576000 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIX_DAT"
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 1048576000 NEXT 1048576000 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIX_DAT"
  REFRESH FAST ON DEMAND NEXT null
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  DISABLE QUERY REWRITE
  AS SELECT "MPUSNTAB"."SNCODE" "SNCODE","MPUSNTAB"."DES" "DES","MPUSNTAB"."SHDES" "SHDES","MPUSNTAB"."SNIND" "SNIND","MPUSNTAB"."REC_VERSION" "REC_VERSION",
  "MPUSNTAB"."PDE_IMPLICIT_IND" "PDE_IMPLICIT_IND","MPUSNTAB"."SNTYPE" "SNTYPE","MPUSNTAB"."PRINT_BALANCE_IND" "PRINT_BALANCE_IND",
  "MPUSNTAB"."IMPORT_EXPORT_FLAG" "IMPORT_EXPORT_FLAG","MPUSNTAB"."SERVICE_GROUP_ID" "SERVICE_GROUP_ID","MPUSNTAB"."SALES_VALUES_FLAG" "SALES_VALUES_FLAG",
  "MPUSNTAB"."SNCODE_SWAP_TARGET" "SNCODE_SWAP_TARGET"
  FROM "SYSADM"."MPUSNTAB"@LNK.MIT08 "MPUSNTAB"
  /



  CREATE MATERIALIZED VIEW "BIX"."MV_MPUZNTAB"
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 1048576000 NEXT 1048576000 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIX_DAT"
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 1048576000 NEXT 1048576000 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIX_DAT"
  REFRESH FAST ON DEMAND NEXT null
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  DISABLE QUERY REWRITE
  AS SELECT "MPUZNTAB"."ZNCODE" "ZNCODE","MPUZNTAB"."DES" "DES","MPUZNTAB"."SHDES" "SHDES","MPUZNTAB"."REC_VERSION" "REC_VERSION","MPUZNTAB"."GVZN_SHDES" "GVZN_SHDES","MPUZNTAB"."IMPORT_EXPORT_FLAG" "IMPORT_EXPORT_FLAG" 
  FROM "SYSADM"."MPUZNTAB"@LNK.MIT08 "MPUZNTAB"
  /



  CREATE MATERIALIZED VIEW "BIX"."MV_MPUZOTAB"
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 1048576000 NEXT 1048576000 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIX_DAT"
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 1048576000 NEXT 1048576000 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIX_DAT"
  REFRESH FAST ON DEMAND NEXT null
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  DISABLE QUERY REWRITE
  AS SELECT "MPUZOTAB"."ZOCODE" "ZOCODE","MPUZOTAB"."DES" "DES","MPUZOTAB"."CGI" "CGI","MPUZOTAB"."SCCODE" "SCCODE","MPUZOTAB"."REC_VERSION" "REC_VERSION","MPUZOTAB"."ORIGIN_NPCODE" "ORIGIN_NPCODE","MPUZOTAB"."SHDES" "SHDES","MPUZOTAB"."IMPORT_EXPORT_FLAG" "IMPORT_EXPORT_FLAG" 
  FROM "SYSADM"."MPUZOTAB"@LNK.MIT08 "MPUZOTAB"
  /
  

  CREATE MATERIALIZED VIEW "BIX"."MV_MPUZPTAB"
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 1048576000 NEXT 1048576000 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIX_DAT"
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 1048576000 NEXT 1048576000 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIX_DAT"
  REFRESH FAST ON DEMAND NEXT null
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  DISABLE QUERY REWRITE
  AS SELECT "MPUZPTAB"."ZPCODE" "ZPCODE","MPUZPTAB"."DES" "DES","MPUZPTAB"."DIGITS" "DIGITS","MPUZPTAB"."ZP_INTERNAL_FLAG" "ZP_INTERNAL_FLAG","MPUZPTAB"."DEST_NPCODE" "DEST_NPCODE","MPUZPTAB"."REC_VERSION" "REC_VERSION","MPUZPTAB"."SHDES" "SHDES","MPUZPTAB"."IMPORT_EXPORT_FLAG" "IMPORT_EXPORT_FLAG" 
  FROM "SYSADM"."MPUZPTAB"@LNK.MIT08 "MPUZPTAB"
  /
  

  CREATE MATERIALIZED VIEW "BIX"."MV_PORT"
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 1048576000 NEXT 1048576000 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIX_DAT"
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 1048576000 NEXT 1048576000 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIX_DAT"
  REFRESH FAST ON DEMAND NEXT null
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  DISABLE QUERY REWRITE
  AS SELECT "PORT"."PORT_ID" "PORT_ID","PORT"."PLCODE" "PLCODE","PORT"."HLCODE" "HLCODE","PORT"."PORT_NUM" "PORT_NUM","PORT"."PORT_STATUS" "PORT_STATUS","PORT"."PORT_STATUSMODDAT" "PORT_STATUSMODDAT","PORT"."PORT_KI" "PORT_KI","PORT"."PORT_KIND" "PORT_KIND","PORT"."PORT_CHANNELS" "PORT_CHANNELS","PORT"."PORT_CHANNELS_EXCL" "PORT_CHANNELS_EXCL","PORT"."SM_ID" "SM_ID","PORT"."PORT_SM_REQU" "PORT_SM_REQU","PORT"."SIMPOH_ID" "SIMPOH_ID","PORT"."SIMPOT_ID" "SIMPOT_ID","PORT"."SIMPOT_BATCH" "SIMPOT_BATCH","PORT"."DN_ID" "DN_ID","PORT"."DEALER_ID" "DEALER_ID","PORT"."PORT_ASSIGN_DATE" "PORT_ASSIGN_DATE","PORT"."PORT_TKEY" "PORT_TKEY","PORT"."PORT_STATUS_REQU" "PORT_STATUS_REQU","PORT"."PORT_STA_REQU_DATE" "PORT_STA_REQU_DATE","PORT"."PORT_ACTIV_DATE" "PORT_ACTIV_DATE","PORT"."PORT_DEACTIV_DATE" "PORT_DEACTIV_DATE","PORT"."PORT_ENTDATE" "PORT_ENTDATE","PORT"."PORT_MODDATE" "PORT_MODDATE","PORT"."PORT_USERLASTMOD" "PORT_USERLASTMOD","PORT"."PRE_ACTIVATED" "PRE_ACTIVATED","PORT"."SMS_UPDATE" "SMS_UPDATE","PORT"."PORT_RIC_BATCH" "PORT_RIC_BATCH","PORT"."EXTERNAL_IND" "EXTERNAL_IND","PORT"."CAPACITY" "CAPACITY","PORT"."AVAILABLE_CAPACITY" "AVAILABLE_CAPACITY","PORT"."PRM_VALUE_ID" "PRM_VALUE_ID","PORT"."REC_VERSION" "REC_VERSION","PORT"."PORT_NPCODE" "PORT_NPCODE","PORT"."TRANSACTION_ID" "TRANSACTION_ID","PORT"."BUSINESS_UNIT_ID" "BUSINESS_UNIT_ID","PORT"."GHLCODE" "GHLCODE" 
  FROM "SYSADM"."PORT"@LNK.MIT08 "PORT"
  /
  



  CREATE MATERIALIZED VIEW "BIX"."MV_PR_SERV_SPCODE_HIST"
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 1048576000 NEXT 1048576000 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIX_DAT"
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 1048576000 NEXT 1048576000 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIX_DAT"
  REFRESH FAST ON DEMAND NEXT null
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  DISABLE QUERY REWRITE
  AS SELECT "PR_SERV_SPCODE_HIST"."PROFILE_ID" "PROFILE_ID","PR_SERV_SPCODE_HIST"."CO_ID" "CO_ID","PR_SERV_SPCODE_HIST"."SNCODE" "SNCODE","PR_SERV_SPCODE_HIST"."HISTNO" "HISTNO","PR_SERV_SPCODE_HIST"."SPCODE" "SPCODE","PR_SERV_SPCODE_HIST"."TRANSACTIONNO" "TRANSACTIONNO","PR_SERV_SPCODE_HIST"."VALID_FROM_DATE" "VALID_FROM_DATE","PR_SERV_SPCODE_HIST"."ENTRY_DATE" "ENTRY_DATE","PR_SERV_SPCODE_HIST"."REQUEST_ID" "REQUEST_ID","PR_SERV_SPCODE_HIST"."REC_VERSION" "REC_VERSION","PR_SERV_SPCODE_HIST"."ENTRY_USER" "ENTRY_USER" 
  FROM "SYSADM"."PR_SERV_SPCODE_HIST"@LNK.MIT08 "PR_SERV_SPCODE_HIST"
  /
  


  CREATE MATERIALIZED VIEW "BIX"."MV_RATEPLAN"
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 1048576000 NEXT 1048576000 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIX_DAT"
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 1048576000 NEXT 1048576000 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIX_DAT"
  REFRESH FAST ON DEMAND NEXT null
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  DISABLE QUERY REWRITE
  AS SELECT "RATEPLAN"."TMCODE" "TMCODE","RATEPLAN"."DES" "DES","RATEPLAN"."SHDES" "SHDES","RATEPLAN"."TMGLOBAL" "TMGLOBAL","RATEPLAN"."REC_VERSION" "REC_VERSION","RATEPLAN"."PRERATED_TAP_RP_IND" "PRERATED_TAP_RP_IND","RATEPLAN"."EXTRNL_RATEPLAN_ID" "EXTRNL_RATEPLAN_ID","RATEPLAN"."PDE_RATEPLAN" "PDE_RATEPLAN","RATEPLAN"."PROVISION_EXT" "PROVISION_EXT","RATEPLAN"."IMPORT_EXPORT_FLAG" "IMPORT_EXPORT_FLAG","RATEPLAN"."SPECIAL_USAGE_IND" "SPECIAL_USAGE_IND","RATEPLAN"."PRICETYPE_ID" "PRICETYPE_ID","RATEPLAN"."OBSERVATION" "OBSERVATION","RATEPLAN"."ATS_PREPAID_IND" "ATS_PREPAID_IND" 
  FROM "SYSADM"."RATEPLAN"@LNK.MIT08 "RATEPLAN"
  /
  



  CREATE MATERIALIZED VIEW "BIX"."MV_RATEPLAN_HIST"
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 1048576000 NEXT 1048576000 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIX_DAT"
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 1048576000 NEXT 1048576000 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIX_DAT"
  REFRESH FAST ON DEMAND NEXT null
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  DISABLE QUERY REWRITE
  AS SELECT "RATEPLAN_HIST"."CO_ID" "CO_ID","RATEPLAN_HIST"."SEQNO" "SEQNO","RATEPLAN_HIST"."TMCODE" "TMCODE","RATEPLAN_HIST"."TMCODE_DATE" "TMCODE_DATE","RATEPLAN_HIST"."USERLASTMOD" "USERLASTMOD","RATEPLAN_HIST"."REC_VERSION" "REC_VERSION","RATEPLAN_HIST"."REQUEST_ID" "REQUEST_ID","RATEPLAN_HIST"."TRANSACTIONNO" "TRANSACTIONNO" 
  FROM "SYSADM"."RATEPLAN_HIST"@LNK.MIT08 "RATEPLAN_HIST"
  /
  


  CREATE MATERIALIZED VIEW "BIX"."MV_RATEPLAN_VERSION"
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 1048576000 NEXT 1048576000 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIX_DAT"
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 1048576000 NEXT 1048576000 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIX_DAT"
  REFRESH FAST ON DEMAND NEXT null
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  DISABLE QUERY REWRITE
  AS SELECT "RATEPLAN_VERSION"."VSCODE" "VSCODE","RATEPLAN_VERSION"."VSDATE" "VSDATE","RATEPLAN_VERSION"."STATUS" "STATUS","RATEPLAN_VERSION"."TMRC" "TMRC","RATEPLAN_VERSION"."APDATE" "APDATE","RATEPLAN_VERSION"."CURRENCY" "CURRENCY","RATEPLAN_VERSION"."REC_VERSION" "REC_VERSION","RATEPLAN_VERSION"."TMCODE" "TMCODE","RATEPLAN_VERSION"."PLCODE" "PLCODE","RATEPLAN_VERSION"."IMPORT_EXPORT_FLAG" "IMPORT_EXPORT_FLAG","RATEPLAN_VERSION"."INT_SYNC" "INT_SYNC","RATEPLAN_VERSION"."OVERWRITE_FLAG" "OVERWRITE_FLAG" 
  FROM "SYSADM"."RATEPLAN_VERSION"@LNK.MIT08 "RATEPLAN_VERSION"
  /
  


  CREATE MATERIALIZED VIEW "BIX"."MV_THSFTTAB"
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 1048576000 NEXT 1048576000 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIX_DAT"
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 1048576000 NEXT 1048576000 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIX_DAT"
  REFRESH FAST ON DEMAND NEXT null
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  DISABLE QUERY REWRITE
  AS SELECT "THSFTTAB"."FT_ID" "FT_ID","THSFTTAB"."IO" "IO","THSFTTAB"."DESCRIPTION" "DESCRIPTION","THSFTTAB"."TYPE" "TYPE","THSFTTAB"."DIRECTORY" "DIRECTORY","THSFTTAB"."PROCESS" "PROCESS","THSFTTAB"."REF_TABLE" "REF_TABLE","THSFTTAB"."RECYCLING_IND" "RECYCLING_IND","THSFTTAB"."SPLIT_TRANSACTION_IND" "SPLIT_TRANSACTION_IND","THSFTTAB"."COLLECT_RECORD_IND" "COLLECT_RECORD_IND","THSFTTAB"."MAXIMAL_TRANSACTION_SIZE" "MAXIMAL_TRANSACTION_SIZE","THSFTTAB"."MAXIMAL_COLLECTION_TIME" "MAXIMAL_COLLECTION_TIME","THSFTTAB"."REC_VERSION" "REC_VERSION","THSFTTAB"."EXCHANGE_FORMAT_ID" "EXCHANGE_FORMAT_ID","THSFTTAB"."IMP_CHANNEL_ID" "IMP_CHANNEL_ID","THSFTTAB"."SOURCE_NETWORK_CODE" "SOURCE_NETWORK_CODE","THSFTTAB"."HOME_NETWORK_CODE" "HOME_NETWORK_CODE","THSFTTAB"."FILE_SOURCE" "FILE_SOURCE","THSFTTAB"."EXT_APPLICATION_TYPE_NAME" "EXT_APPLICATION_TYPE_NAME","THSFTTAB"."BLKSIZE" "BLKSIZE","THSFTTAB"."VENDCODE" "VENDCODE","THSFTTAB"."SMC_ID" "SMC_ID","THSFTTAB"."RAL_REPROCESS_FLAG" "RAL_REPROCESS_FLAG" 
  FROM "SYSADM"."THSFTTAB"@LNK.MIT08 "THSFTTAB"
  /
  


  CREATE MATERIALIZED VIEW "BIX"."MV_THUFITAB"
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 1048576000 NEXT 1048576000 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIX_DAT"
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 1048576000 NEXT 1048576000 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIX_DAT"
  REFRESH FAST ON DEMAND NEXT null
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  DISABLE QUERY REWRITE
  AS SELECT "THUFITAB"."FILE_ID" "FILE_ID","THUFITAB"."FILE_TYPE" "FILE_TYPE","THUFITAB"."FILENAME" "FILENAME","THUFITAB"."RECEIVED" "RECEIVED","THUFITAB"."STATUS" "STATUS","THUFITAB"."BLKSIZE" "BLKSIZE","THUFITAB"."FLJOB" "FLJOB","THUFITAB"."IMPORT_FUNCTION_ID" "IMPORT_FUNCTION_ID","THUFITAB"."REC_VERSION" "REC_VERSION","THUFITAB"."NETWORK_ELEMENT_ID" "NETWORK_ELEMENT_ID","THUFITAB"."RAP_FLAG" "RAP_FLAG","THUFITAB"."TOTAL_CHARGE" "TOTAL_CHARGE","THUFITAB"."BASE_CHARGE" "BASE_CHARGE","THUFITAB"."INTERCONNECT_CHARGE" "INTERCONNECT_CHARGE","THUFITAB"."CURRENCY" "CURRENCY" 
  FROM "SYSADM"."THUFITAB"@LNK.MIT08 "THUFITAB"
  /
  

  CREATE MATERIALIZED VIEW "BIX"."MV_UDC_RATE_TYPE_TABLE"
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 1048576000 NEXT 1048576000 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIX_DAT"
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 1048576000 NEXT 1048576000 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIX_DAT"
  REFRESH FAST ON DEMAND NEXT null
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  DISABLE QUERY REWRITE
  AS SELECT "UDC_RATE_TYPE_TABLE"."RATE_TYPE_ID" "RATE_TYPE_ID","UDC_RATE_TYPE_TABLE"."RATE_TYPE_DES" "RATE_TYPE_DES","UDC_RATE_TYPE_TABLE"."RATE_TYPE_SHNAME" "RATE_TYPE_SHNAME","UDC_RATE_TYPE_TABLE"."FALLBACK_RATE_TYPE_ID" "FALLBACK_RATE_TYPE_ID","UDC_RATE_TYPE_TABLE"."INTERCONNECT_RATING_IND" "INTERCONNECT_RATING_IND","UDC_RATE_TYPE_TABLE"."DEPENDENT_RATE_TYPE_ID" "DEPENDENT_RATE_TYPE_ID" 
  FROM "SYSADM"."UDC_RATE_TYPE_TABLE"@LNK.MIT08 "UDC_RATE_TYPE_TABLE"
  /
  
